appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ruu2Qd8HeQvMGXvp/9cONwtzM7pPLGrnAK2ecb+l8xQJdRSarQ+BuEdCsRVbywJNiPYhR9QrePasdnlrVXFJGzsIbA7LcGfH7Tb27cFdug8joRHPKwViTpdIXD6JQ8r3F+wOKbqhMedG1HtAGtzFa8p0rTUo5wBnm8E6Z9ogtQPiCTkIByP2hX1Uz46HOcZYai+ssLtCPq9ycPrYjJ94MhDzM7gcfLWtiAHtlq1/i0y5lW2NKAKSbgNTzabYHQl8CZqijj+0zotBpP8jXtSU7x+FBoKaFXqnM9eC1yQ7liT14hHe/HwMdY8WLbl63ECz1SrVFiC78ZMDjXSw5WCczOAnfkybyzqOnOoVWv4YE8fRW1nDTzCrOWnSye+dBz3AMtwGYm1v4LL1IAa3pyI8MqDairBziLfX9qHu5OLWzLbbDkfGsrbbhYiOXaI+TEDMQDsCeRNsiSk3QLxG2X4/kwpxJ9FME7yhwKGSy7rQbsoW2ND+/eDeL+ra3JpxxAnGtznglxGC4hD7VsNZI60+EuvnaA6nH7afu0TaAC0N51cv3Snzl27jyef3yLObZOHdzc8Xair7R/5zv/JxEFJhmZV+KwK7Ellx0H6GPtYjH46IVUTpHewLduRxwemTAJV0LiNaORXN1R13HlvXLQwNsyldr9Eij7toYdB7FkcnRcU=}
conda_forge_output_validation: true
