travis:
  secure:
    BINSTAR_TOKEN: EV+z/CvVq4vjQlrbA3eKIzPs6/0XFo5sMiCVi2btgGkQmvTTDxHet12ymdQid8fYX3l8SF3zTQlcBx/LzuZ4z7G0H+SEoAGsyoSwW7LhHXepVgz+fdfWgxl12k7EgqAkNKJCKvaq1B76llW3Pam3f0DQHgrf8J8krGY2qPck35adSdC6P+nJbaTepVN1BS5f6gc48PuUZ9eJORWuU+bQO4Bmb0f2eCrJ2h5vKWZUk276JUHZaBIMH0YIriyJvHNdvEm7Musw7Aya/cAOWmhOwEmQuVK5rmC+4sR3YXfkvVhAcmgDvhI8qml3LfQmNUn+r7jeb4LUnVOMkiL5eJI+AjDul/3z34dYO/LayfrtdCOyzggj1XM/uLnWUJHHAncdZgA6cyyazn8znSWXh2EEJtxZ6IlvLEZGhn9I4aWe12ObLjNCUUZ8ho7EjbavOLzcq/UHL+Q4pQDOR5ETvYiNei3UqlI1Z9sc/8SZV/1Oysv/MFufqCEPGCcalhxyZyswRhH0CYVPPPpiubr47YycTWzHFEOcTSkpFbHLkTh0Sk9cqA1L5CwCgV3Agmhs4Yag2nErt0z4pj5t1cK49iIoCmyoGfZzRIjDyyA4IaLcHQi/to7NVWKuH2FlBeJFbxwaHb87i111AZCaYaEPoxTcF9Oa8hmX4R2e8FduAfBBtkA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
